export const FETCH_SALES_TREND_START = 'kpi/FETCH_SALES_TREND_START'
export const FETCH_SALES_TREND_SUCCESS = 'kpi/FETCH_SALES_TREND_SUCCESS'
export const FETCH_SALES_TREND_FAILED = 'kpi/FETCH_SALES_TREND_FAILED'