export const FETCH_SALES_BY_CATEGORY_START = 'kpi/FETCH_SALES_BY_CATEGORY_START'
export const FETCH_SALES_BY_CATEGORY_SUCCESS = 'kpi/FETCH_SALES_BY_CATEGORY_SUCCESS'
export const FETCH_SALES_BY_CATEGORY_FAILED = 'kpi/FETCH_SALES_BY_CATEGORY_FAILED'