export const FETCH_SALES_PER_REGION_START = 'kpi/FETCH_SALES_PER_REGION_START'
export const FETCH_SALES_PER_REGION_SUCCESS = 'kpi/FETCH_SALES_PER_REGION_SUCCESS'
export const FETCH_SALES_PER_REGION_FAILED = 'kpi/FETCH_SALES_PER_REGION_FAILED'