export const FETCH_REVENUE_PER_PRODUCT_START = 'kpi/FETCH_REVENUE_PER_PRODUCT_START'
export const FETCH_REVENUE_PER_PRODUCT_SUCCESS = 'kpi/FETCH_REVENUE_PER_PRODUCT_SUCCESS'
export const FETCH_REVENUE_PER_PRODUCT_FAILED = 'kpi/FETCH_REVENUE_PER_PRODUCT_FAILED'
